/* Project: HelpMojaBibliaNT */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __HelpMojaBibliaNT_HEADER__
#define __HelpMojaBibliaNT_HEADER__

enum {
  HELP_Wprowadzenie = 0,
  HELP_Mozliwosciaplikacji = 1,
  HELP_Jakzaczac = 2,
  HELP_Wymagania = 3,
  HELP_Wygladaplikacji = 4,
  HELP_WczytywanieTekstu = 5,
  HELP_Wyszukiwanietekstu = 6,
  HELP_Wyborpojedynczegowersetu = 7,
  HELP_Korkondancjagrecka = 8,
  HELP_Powiazaniemiedzywersetami = 9,
  HELP_PlanczytaniaPisma = 10,
  HELP_Przegladzasobow = 11,
  HELP_Edycjarozdzialu = 12,
  HELP_Wysylaniewybranegorozdzialuemail = 13,
  HELP_Tworzeniegrafikiztekstem = 14,
  HELP_Ustawieniaaplikacji = 15,
  HELP_Wygladaplikacji1 = 16,
  HELP_Flagiiprzelaczniki = 17,
  HELP_Sciezkidostepu = 18,
  HELP_Inneustawienia = 19,
  HELP_Wybortlumaczen = 20,
  HELP_PlanczytaniaBiblii = 21,
  HELP_Tematygraficzne = 22
};

#endif
