object ChapterEditWindow: TChapterEditWindow
  Left = 0
  Top = 0
  Caption = 'ChapterEditWindow'
  ClientHeight = 820
  ClientWidth = 1240
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Font.Quality = fqClearType
  Position = poScreenCenter
  OnActivate = FormActivate
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  TextHeight = 13
end
